void setup(){
  //1.
size(500,500); 
}
void draw(){
ellipse(50,mouseY,mouseY,mouseY);
ellipse(100,mouseY,mouseY,mouseY);
ellipse(150,mouseY,mouseY,mouseY);
ellipse(200,mouseY,mouseY,mouseY);
ellipse(250,mouseY,mouseY,mouseY);
ellipse(300,mouseY,mouseY,mouseY);
ellipse(350,mouseY,mouseY,mouseY);
ellipse(400,mouseY,mouseY,mouseY);
ellipse(450,mouseY,mouseY,mouseY);
ellipse(500,mouseY,mouseY,mouseY);
ellipse(55,mouseY,mouseY,mouseY);
ellipse(105,mouseY,mouseY,mouseY);
ellipse(155,mouseY,mouseY,mouseY);
ellipse(205,mouseY,mouseY,mouseY);
ellipse(255,mouseY,mouseY,mouseY);
ellipse(305,mouseY,mouseY,mouseY);
ellipse(355,mouseY,mouseY,mouseY);
ellipse(405,mouseY,mouseY,mouseY);
ellipse(50,mouseY,mouseY,mouseY);
ellipse(100,mouseY,mouseY,mouseY);
ellipse(150,mouseY,mouseY,mouseY);
ellipse(200,mouseY,mouseY,mouseY);
ellipse(250,mouseY,mouseY,mouseY);
ellipse(300,mouseY,mouseY,mouseY);
ellipse(350,mouseY,mouseY,mouseY);
ellipse(400,mouseY,mouseY,mouseY);
ellipse(450,mouseY,mouseY,mouseY);
ellipse(500,mouseY,mouseY,mouseY);
ellipse(55,mouseY,mouseY,mouseY);
ellipse(105,mouseY,mouseY,mouseY);
ellipse(155,mouseY,mouseY,mouseY);
ellipse(205,mouseY,mouseY,mouseY);
ellipse(255,mouseY,mouseY,mouseY);
ellipse(305,mouseY,mouseY,mouseY);
ellipse(355,mouseY,mouseY,mouseY);
ellipse(405,mouseY,mouseY,mouseY);

if(mousePressed){
  fill(255,0,0);
}else{
 
  fill(0,0,255);
}
}